CREATE TABLE OPERATOR_ORDER
(
    ORDER_ID            SERIAL PRIMARY KEY,
    CLEANING_DATE       TIMESTAMP,
    ADDRESS             VARCHAR(100),
    TYPE_CLEANING       VARCHAR(30),
    TYPE_OBJECT         VARCHAR(20),
    PAYMENT_AMOUNT      INT,
    PAYMENT_METHOD      VARCHAR(20),
    CLIENT_NAME         VARCHAR(100),
    COUNTERPARTY        VARCHAR(50),
    ORDER_SOURCE        VARCHAR(40),
    COMMENT             VARCHAR(200),
    ORDER_CREATION_TIME TIMESTAMP,
    ORDER_AUTHOR        VARCHAR(12),
    DENIED              BOOLEAN DEFAULT FALSE,
    APPROVE             BOOLEAN DEFAULT FALSE,
    COMPLETE            BOOLEAN DEFAULT FALSE,
    DENIED_COMMENT      VARCHAR(200)

);



