CREATE TABLE PARTNERS
(
    CHAT_ID           INT PRIMARY KEY,
    COUNT_ORDERS      INT NOT NULL DEFAULT 0,
    BALANCE           INT NOT NULL DEFAULT 0,
    CASHOUT_STATUS    BOOLEAN NOT NULL DEFAULT FALSE,
    FULL_NAME         VARCHAR (300),
    PHONE_NUMBER      VARCHAR (10),
    EMAIL             VARCHAR (100),
    CARD_NUMBER       VARCHAR (16)
);

COMMENT ON TABLE PARTNERS IS 'Партнеры';
COMMENT ON COLUMN PARTNERS.CHAT_ID IS 'ChatId партнера';
COMMENT ON COLUMN PARTNERS.COUNT_ORDERS IS 'Количество предложеий';
COMMENT ON COLUMN PARTNERS.BALANCE IS 'Текущий баланс';
COMMENT ON COLUMN PARTNERS.CASHOUT_STATUS IS 'Готовность вывода средств';
COMMENT ON COLUMN PARTNERS.FULL_NAME IS 'ФИО партнера';
COMMENT ON COLUMN PARTNERS.PHONE_NUMBER IS 'Телефонный номер';
COMMENT ON COLUMN PARTNERS.EMAIL IS 'email партнера';
COMMENT ON COLUMN PARTNERS.CARD_NUMBER IS 'Номер карты киента для вывода баланса';
