CREATE TABLE OPERATOR_ORDER
(
    ORDER_ID            SERIAL PRIMARY KEY,
    CLEANING_DATE       TIMESTAMP,
    ADDRESS             VARCHAR(300),
    TYPE_CLEANING       VARCHAR(100),
    TYPE_OBJECT         VARCHAR(100),
    PAYMENT_AMOUNT      INT,
    PAYMENT_METHOD      VARCHAR(30),
    CLIENT_NAME         VARCHAR(100),
    COUNTERPARTY        VARCHAR(50),
    ORDER_SOURCE        VARCHAR(50),
    COMMENT             VARCHAR(500),
    ORDER_CREATION_TIME TIMESTAMP,
    ORDER_AUTHOR        VARCHAR(50),
    DENIED              BOOLEAN DEFAULT FALSE,
    APPROVE             BOOLEAN DEFAULT FALSE,
    COMPLETE            BOOLEAN DEFAULT FALSE,
    DENIED_COMMENT      VARCHAR(200)

);



